POST https://localhost/eletsa-api/php/payment/notify.php
# POST https://eletsa.cairns.co.za/php/payment/notify.php
Content-Type: application/x-www-form-urlencoded

PAYGATE_ID=10011072130&PAY_REQUEST_ID=A18E4632-56E1-948C-0580-7F5F1F172F17&REFERENCE=10&TRANSACTION_STATUS=1&RESULT_CODE=990017&AUTH_CODE=5T8A0Z&CURRENCY=ZAR&AMOUNT=3299&RESULT_DESC=Auth+Done&TRANSACTION_ID=78705178&RISK_INDICATOR=AX&PAY_METHOD=CC&PAY_METHOD_DETAIL=Visa&CHECKSUM=f57ccf051307d8d0a0743b31ea379aa1
