POST http://eletsa.cairns.co.za/php/cart/api.php/carttoorder
app_id: e671937d-54c9-11f0-9ec0-1a220d8ac2c9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOm51bGwsInN1YiI6bnVsbCwiYXVkIjpudWxsLCJleHAiOjE4MTMzNzc4MjksIm5iZiI6MTc1Mjg5NzgyOSwiaWF0IjoxNzUyODk3ODI5LCJqdGkiOiJ7NTlGNjI5QzUtRkE5QS0yRjc4LUI5NTYtOTZENjE1Mzc3MzcxfSIsImRhdGEiOnsiaWQiOjE1MjcsInVzZXJuYW1lIjoiQ2Fpcm5zd20iLCJmaXJzdG5hbWUiOiJXaWxsaWFtIiwibGFzdG5hbWUiOiJDYWlybnMiLCJyb2xlaWQiOm51bGwsInJvbGUiOiJVc2VyIiwicGVybWlzc2lvbnMiOltdfX0.NzE5ZDA2OTU1NGJmYzBhNDgzYWQ1Y2M0YTkwMDY3NzhmYjNmYzRlZDA0NDNmYzhlMjVjZjY2YTYyZDhlNTA0YQ
